name: Ingest scc-covid data

on:
  push:
    branches:
      - trunk

  schedule:
    # See table of scheduled times in the README.  Times here are UTC.
    - cron: '0 6,18 * * *'

  # Manually triggered using `./bin/trigger ingest`
  repository_dispatch:
    types: ingest

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: ingest
      run: |
        scripts/fetch-datasets.bash raw-datasets
